services:
  
  groupoffice:
    image: intermesh/groupoffice:latest
    container_name: group-office
    restart: unless-stopped
    ports:
      - "7000:80"
    links:
      - db
    volumes:
      - godata:/var/lib/groupoffice:cached
      - goetc:/etc/groupoffice:cached
#      Example for ssl
#      - "./config/ssl/groupoffice:/etc/ssl/groupoffice"
    env_file:
      - ./db.env  

  db:
    image: mariadb:latest
    container_name: db
    restart: unless-stopped    
    env_file:
      - ./db.env
    environment:
      MYSQL_ROOT_PASSWORD: groupoffice
      MARIADB_AUTO_UPGRADE: 1
    volumes:
      - dbdata:/var/lib/mysql:cached
      
volumes:
  godata:
  goetc:
  dbdata:
  
  
